export const MOVIE_LIST = {
    START: 'MOVIE_LIST_START',
    SUCCESS: 'MOVIE_LIST_SUCCESS',
    FAILURE: 'MOVIE_LIST_FAILURE',
};
export const MOVIE_DETAIL = {
    START: 'MOVIE_DETAIL_START',
    SUCCESS: 'MOVIE_DETAIL_SUCCESS',
    FAILURE: 'MOVIE_DETAIL_FAILURE',
};
